# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# A sentence like as "xho95 = Programmer(with: Swift)" can't use with Jekyll.

# Site settings
title: xho95's Swift Life
email: xho1995@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  let me = Programmer(with: .swift)

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xho95.github.io" # the base hostname & protocol for your site

repository: xho95/xho95.github.io

twitter_username: xho95
github_username:  xho95
facebook_username: xho1995

# set timezone
timezone: Asia/Seoul

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
production_url : https://xho95.github.io

# Includes an icon in the footer for each username you enter
# footer-links:
#   dribbble:
#   email: xho1995@gmail.com
#   facebook: xho1995
#   flickr:
#   github: xho95
#   instagram:
#   linkedin:
#   pinterest:
#   rss: # just type anything here for a working RSS icon
#   twitter: xho95
#   stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
#   youtube: # channel/<your_long_string> or user/<user-name>
#   googleplus: xho95 # anything in your profile username that comes after plus.google.com/

# Build settings
# redcarpet:
#  extensions: ["tables", "autolink", "strikethrough", "space_after_header", "fenced_code_blocks", "footnotes"]

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true

collections:
#  docs:
#    output: true
  posts:
#    permalink: "/:collection/:path/"
    output: true

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate-v2

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: xho95githubio

# google search console
google_verification: JM4y4DtsPxlc9mu0woL1luHlLdgkNbgJMUWf2zBbTJc

# Just the Docs
theme: just-the-docs
# remote_theme: just-the-docs/just-the-docs
# remote_theme: just-the-docs

# Collections 
just_the_docs:
  collections:
#    lists:  
#      name: List
#    docs:
#      name: Docs
    posts:
      name: Legacies
      nav_fold: true

# Callouts
callouts:
  comment:
    title: Comment
    color: grey-lt
  note:
    title: Note
    color: grey-dk
  experiment:
    title: Experiment
    color: grey-dk
  info:
    title: Information
    color: green
  know-how:
    title: Know How
    color: blue
  caution:
    title: Caution
    color: yellow
  important:
    title: Important
    color: purple
  warning:
    title: Test
    color: red

# aux_links: 
#  "About":
#    - "/about/"

# search
search_enabled: true
search.heading_level: 2
search.tokenizer_separator: /[\s/]+/

# Pagination
# pagination:  
#  enabled: true
#  per_page: 10
#  permalink: '/page/:num/'
#  trail:
#    before: 2
#    after: 2

pagination:
  enabled: true 
  collection: 'posts'
  permalink: 'lists/:num/' 
  category: 'posts' 
  per_page: 5
  sort_reverse: true 
  sort_field: 'date' 
  title: 'Blog' 
  limit: 0 
  tag: ''
  trail:
    before: 2
    after: 2
  extension: html 